### ISSUE TITLE
[packages/animate] promise resolves without a value

### ISSUE THREAD

**Issue by ghost** [ThrivingKings/animo#16]
Using `animate` currently requires one to maintain an an identifier to reference to the element being animated on order to do something useful with it once a transition is complete. This is because the promise resolves _without_ a return value. Is there a specific reason for that? Or could the element or elements (e.g. `NodeList`) under operation be returned in the resolved promise, eliminating the need to maintain a reference?

**Sidebar:** Do you recommend any animation libraries to use with the `animate` package? As it stands I'm trying to use [Animate.css](https://daneden.github.io/animate.css/) but I'm sure there's something better out there I just don't know about yet. I'd love to be able to somehow use animo alongside something [animateplus](https://github.com/bendc/animateplus), which doesn't currently support promises but gives programmatic control over animations (including duration).

**Comment by ThrivingKings** [comment]
The resolve _should always_ return the element (see: https://github.com/ThrivingKings/animo/blob/master/packages/animo/src/index.js#L127) but I do think it's a good idea to keep a reference to the DOM element, and consider reselecting it in order to have the most current reference available. I'm not able to troubleshoot at the moment, but I can look into this a little further later. If you can provide any code snippets, that'd be helpful too.

I like to use Animate.css just because it's easy but you may find that you want to write your own animo plugins. The `animate` plugin is great if you want to do something after an animation has finished but if you're looking for something more elaborate, you could create multiple plugins that do specific things, chaining them with animo.

```js
import animo from 'animo-core'

const growItem = el => {
  return new animo(el, {
    iterate: 10,
    onIteration: function(element) {
      /* use element.transform() to grow it slightly each time */
    }
  })
}

const moveItem = el => {
  return new animo(el, {
    iterate: 10,
    onIteration: function(element) {
      /* use element.transform() to move it slightly each time */
    }
  })
}

const myElement = document.querySelector('.my-element')

growItem(myElement)
  .then(() => {
    /* handle computations, or maybe require user input */
    moveItem(myElement)
      .then(() => {
        /* ... */
      })
  })
```

**Comment by ghost** [comment]
Gorgeous work. Somehow I missed the return in the Promise. Likely a derp on my end. Looking forward to helping build out more plugins, help build exposire and advance the project where I can. Also, thanks for the additional tips.

The name animo keeps reminding me of "Dynamo" from the Running Man film. Both can sing.
